module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#0033FF",
      },
      fontFamily: {
        soehne: [
          "Söhne",
          "Söhne Mono",
          "Mi Sans",
          "PingFang SC",
          "Microsoft YaHei",
          "Hiragino Sans",
          "Noto Sans CJK SC",
          "Noto Sans JP",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
        soehneMono: [
          "Söhne Mono",
          "Söhne",
          "Mi Sans",
          "PingFang SC",
          "Microsoft YaHei",
          "Hiragino Sans",
          "Noto Sans CJK SC",
          "Noto Sans JP",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
        miSans: [
          "Mi Sans",
          "PingFang SC",
          "Microsoft YaHei",
          "Hiragino Sans",
          "Noto Sans CJK SC",
          "Noto Sans JP",
          "Helvetica Neue",
          "Arial",
          "sans-serif",
        ],
      },
    },
  },
  plugins: [],
};
